[package]
name = "skrepka_core"
crate = "skrepka_core"
version = "0.1.0"
repository = "https://github.com/ilyakooo0/skrepka"
license = "MIT"

[cargo]
global_args = []

[cargo.command_args]
build = ["--features", "facet_typegen"]

[targets.apple]
output = "../apple/generated/Shared"
deployment_target = "17.0"
include_macos = false

[targets.apple.swift]
module_name = "SkrepkaShared"

[targets.apple.spm]
package_name = "SkrepkaShared"
layout = "ffi-only"
